# Generated by Django 5.2.4 on 2025-07-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
