# Generated by Django 5.2.4 on 2025-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userextend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='monthly_budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
