# Generated by Django 5.2.4 on 2025-08-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], default=None, max_length=20)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('destination_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='accounts.account')),
                ('origin_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origin_account', to='accounts.account')),
            ],
        ),
    ]
