# Generated by Django 5.2.4 on 2025-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=20)),
            ],
        ),
    ]
